FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime as base

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    git \
    libglib2.0-0 \
    tree \
    less \
    vim \
    curl \
    wget \
    build-essential \
    python3-pip \
    mesa-utils \
    sudo \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copying requirements and installing them
COPY ./requirements/kandinskiy-requirements.txt .
RUN pip install -r kandinskiy-requirements.txt

# Copying rest of project and installing it
COPY  ./bdsm_project ./bdsm_project
COPY ./setup.py .
RUN pip install -e .

ENTRYPOINT python3 -m bdsm_project.models.kandinskiy.server